CREATE PROCEDURE [dbo].[MoveTickerReferenceToArchive]
	
AS
	insert into dbo.TickerReferenceArchive (
	   [RunDate]
      ,[Ticker]
      ,[TickerRoot]
      ,[Name]
      ,[Description]
      ,[ListDate]
      ,[Locale]
      ,[Market]
      ,[Cik]
      ,[ShareClassFigi]
      ,[CompositeFigi]
      ,[CurrencyName]
      ,[MarketCap]
      ,[SicCode]
      ,[SicDescription]
      ,[PrimaryExchange]
      ,[ShareClassSharesOutstanding]
      ,[Type]
      ,[WeightedSharesOutstanding]
      ,[RoundLot]
	)
   select  [RunDate]
      ,[Ticker]
      ,[TickerRoot]
      ,[Name]
      ,[Description]
      ,[ListDate]
      ,[Locale]
      ,[Market]
      ,[Cik]
      ,[ShareClassFigi]
      ,[CompositeFigi]
      ,[CurrencyName]
      ,[MarketCap]
      ,[SicCode]
      ,[SicDescription]
      ,[PrimaryExchange]
      ,[ShareClassSharesOutstanding]
      ,[Type]
      ,[WeightedSharesOutstanding]
      ,[RoundLot]
      from dbo.TickerReference

      delete from dbo.TickerReference
