CREATE VIEW [pgon].[TickerAnalytics]
	AS
	
	SELECT 
	Ticker,
	[Open],
	[Close],
	[Date],
	ROUND(AVG([Close]) OVER (PARTITION BY Ticker ORDER BY [Date] ROWS BETWEEN 5 PRECEDING and 1 PRECEDING),2) AS SMA5,
	ROUND(AVG([Close]) OVER (PARTITION BY Ticker ORDER BY [Date] ROWS BETWEEN 10 PRECEDING and  1 PRECEDING),2) AS SMA10,
	ROUND(AVG([Close]) OVER (PARTITION BY Ticker ORDER BY [Date] ROWS BETWEEN 20 PRECEDING and  1 PRECEDING),2) AS SMA20,
	ROUND(AVG([Close]) OVER (PARTITION BY Ticker ORDER BY [Date] ROWS BETWEEN 50 PRECEDING and  1 PRECEDING),2) AS SMA50,
	ROUND(AVG([Close]) OVER (PARTITION BY Ticker ORDER BY [Date] ROWS BETWEEN 100 PRECEDING and  1 PRECEDING),2) AS SMA100,
	ROUND(AVG([Close]) OVER (PARTITION BY Ticker ORDER BY [Date] ROWS BETWEEN 200 PRECEDING and  1 PRECEDING),2) AS SMA200,
	ROUND(AVG([VolumeWeighted]) OVER (PARTITION BY Ticker ORDER BY [Date] ROWS BETWEEN 5 PRECEDING and  1 PRECEDING),2) AS VWMA5,
	ROUND(AVG([VolumeWeighted]) OVER (PARTITION BY Ticker ORDER BY [Date] ROWS BETWEEN 10 PRECEDING and  1 PRECEDING),2) AS VWMA10,
	ROUND(AVG([VolumeWeighted]) OVER (PARTITION BY Ticker ORDER BY [Date] ROWS BETWEEN 20 PRECEDING and  1 PRECEDING),2) AS VWMA20,
	ROUND(AVG([VolumeWeighted]) OVER (PARTITION BY Ticker ORDER BY [Date] ROWS BETWEEN 50 PRECEDING and  1 PRECEDING),2) AS VWMA50,
	ROUND(AVG([VolumeWeighted]) OVER (PARTITION BY Ticker ORDER BY [Date] ROWS BETWEEN 100 PRECEDING and  1 PRECEDING),2) AS VWMA100,
	ROUND(AVG([VolumeWeighted]) OVER (PARTITION BY Ticker ORDER BY [Date] ROWS BETWEEN 200 PRECEDING and  1 PRECEDING),2) AS VWMA200
	FROM pgon.DailySnapShotPricesMemOpt
