CREATE TABLE [curve].[TreasuryYieldCurve]
(
	[TreasuryYieldCurveId] INT NOT NULL PRIMARY KEY identity(1,1),
	[Date] Date NOT NULL,
	[1M] FLOAT NULL DEFAULT 0,
	[2M] FLOAT NULL DEFAULT 0,
	[3M] FLOAT NULL DEFAULT 0,
	[4M] FLOAT NULL DEFAULT 0,
	[6M] FLOAT NULL DEFAULT 0,
	[1Y] FLOAT NULL DEFAULT 0,
	[2Y] FLOAT NULL DEFAULT 0,
	[3Y] FLOAT NULL DEFAULT 0,
	[5Y] FLOAT NULL DEFAULT 0,
	[7Y] FLOAT NULL DEFAULT 0,
	[10Y] FLOAT NULL DEFAULT 0,
	[20Y] FLOAT NULL DEFAULT 0,
	[30Y] FLOAT NULL DEFAULT 0
)

GO

CREATE UNIQUE INDEX [IX_TreasuryYieldCurve_Column] ON [curve].[TreasuryYieldCurve] ([Date] asc) include([1M],[2M],[3M],[4M],[6M],[1Y],[2Y],[3Y],[5Y],[7Y],[10Y],[20Y],[30Y])
