CREATE TABLE [dbo].[ScreenerTable] (
    -- Primary Key
    [Id] INT IDENTITY(1,1) PRIMARY KEY,
    [CreatedDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
    
    -- Identity / Basic (from FinvizRow)
    [No] INT NULL,
    [Ticker] NVARCHAR(20) NOT NULL,
    [Company] NVARCHAR(255) NULL,
    [Index] NVARCHAR(50) NULL,
    [Sector] NVARCHAR(100) NULL,
    [Industry] NVARCHAR(150) NULL,
    [Country] NVARCHAR(100) NULL,
    [Exchange] NVARCHAR(50) NULL,
    
    -- Valuation / Ratios
    [MarketCap] FLOAT NULL,
    [PE] FLOAT NULL,
    [ForwardPE] FLOAT NULL,
    [PEG] FLOAT NULL,
    [PS] FLOAT NULL,
    [PB] FLOAT NULL,
    [PCash] FLOAT NULL,
    [PFreeCashFlow] FLOAT NULL,
    [BookPerShare] FLOAT NULL,
    [CashPerShare] FLOAT NULL,
    
    -- Dividends
    [Dividend] FLOAT NULL,
    [DividendYield] FLOAT NULL,
    [DividendTTM] FLOAT NULL,
    [DividendExDate] DATETIME2 NULL,
    [DividendGrowth1Year] FLOAT NULL,
    [DividendGrowth3Years] FLOAT NULL,
    [DividendGrowth5Years] FLOAT NULL,
    [PayoutRatio] FLOAT NULL,
    
    -- EPS / Sales
    [EPSTTM] FLOAT NULL,
    [EPSNextQ] FLOAT NULL,
    [EPSGrowthThisYear] FLOAT NULL,
    [EPSGrowthNextYear] FLOAT NULL,
    [EPSGrowthPast3Years] FLOAT NULL,
    [EPSGrowthPast5Years] FLOAT NULL,
    [EPSGrowthNext5Years] FLOAT NULL,
    [SalesGrowthPast3Years] FLOAT NULL,
    [SalesGrowthPast5Years] FLOAT NULL,
    [EPSQoQGrowth] FLOAT NULL,
    [EPSYoYTTM] FLOAT NULL,
    [SalesYoYTTM] FLOAT NULL,
    
    -- Income / Surprises
    [Sales] FLOAT NULL,
    [Income] FLOAT NULL,
    [EPSSurprise] FLOAT NULL,
    [RevenueSurprise] FLOAT NULL,
    
    -- Enterprise / Shares
    [EnterpriseValue] FLOAT NULL,
    [EVToEBITDA] FLOAT NULL,
    [SharesOutstanding] FLOAT NULL,
    [SharesFloat] FLOAT NULL,
    [FloatPercent] FLOAT NULL,
    
    -- Ownership / Short
    [InsiderOwnership] FLOAT NULL,
    [InsiderTransactions] FLOAT NULL,
    [InstitutionalOwnership] FLOAT NULL,
    [InstitutionalTransactions] FLOAT NULL,
    [ShortFloat] FLOAT NULL,
    [ShortRatio] FLOAT NULL,
    [ShortInterest] FLOAT NULL,
    
    -- Profitability / Leverage
    [ReturnOnAssets] FLOAT NULL,
    [ReturnOnEquity] FLOAT NULL,
    [ReturnOnInvestedCapital] FLOAT NULL,
    [CurrentRatio] FLOAT NULL,
    [QuickRatio] FLOAT NULL,
    [LTDebtToEquity] FLOAT NULL,
    [TotalDebtToEquity] FLOAT NULL,
    [GrossMargin] FLOAT NULL,
    [OperatingMargin] FLOAT NULL,
    [ProfitMargin] FLOAT NULL,
    
    -- Performance Metrics
    [Performance1Min] FLOAT NULL,
    [Performance2Min] FLOAT NULL,
    [Performance3Min] FLOAT NULL,
    [Performance5Min] FLOAT NULL,
    [Performance10Min] FLOAT NULL,
    [Performance15Min] FLOAT NULL,
    [Performance30Min] FLOAT NULL,
    [Performance1Hour] FLOAT NULL,
    [Performance2Hours] FLOAT NULL,
    [Performance4Hours] FLOAT NULL,
    [PerformanceWeek] FLOAT NULL,
    [PerformanceMonth] FLOAT NULL,
    [PerformanceQuarter] FLOAT NULL,
    [PerformanceHalfYear] FLOAT NULL,
    [PerformanceYTD] FLOAT NULL,
    [PerformanceYear] FLOAT NULL,
    [Performance3Years] FLOAT NULL,
    [Performance5Years] FLOAT NULL,
    [Performance10Years] FLOAT NULL,
    
    -- Technicals
    [Beta] FLOAT NULL,
    [AverageTrueRange] FLOAT NULL,
    [VolatilityWeek] FLOAT NULL,
    [VolatilityMonth] FLOAT NULL,
    [SMA20Day] FLOAT NULL,
    [SMA50Day] FLOAT NULL,
    [SMA200Day] FLOAT NULL,
    [High50Day] FLOAT NULL,
    [Low50Day] FLOAT NULL,
    [High52Week] FLOAT NULL,
    [Low52Week] FLOAT NULL,
    [Range52Week] NVARCHAR(50) NULL,
    [AllTimeHigh] FLOAT NULL,
    [AllTimeLow] FLOAT NULL,
    [RSI14] FLOAT NULL,
    
    -- Dates / Flags
    [EarningsDate] DATETIME2 NULL,
    [IPODate] DATETIME2 NULL,
    [Optionable] NVARCHAR(10) NULL,
    [Shortable] NVARCHAR(10) NULL,
    
    -- Intraday fields
    [ChangeFromOpen] FLOAT NULL,
    [Gap] FLOAT NULL,
    [AnalystRecom] FLOAT NULL,
    [AverageVolume] FLOAT NULL,
    [RelativeVolume] FLOAT NULL,
    [Volume] FLOAT NULL,
    [Trades] FLOAT NULL,
    [TargetPrice] FLOAT NULL,
    [PrevClose] FLOAT NULL,
    [Open] FLOAT NULL,
    [High] FLOAT NULL,
    [Low] FLOAT NULL,
    [Price] FLOAT NULL,
    [Change] FLOAT NULL,
    
    -- News
    [NewsTime] DATETIME2 NULL,
    [NewsURL] NVARCHAR(500) NULL,
    [NewsTitle] NVARCHAR(500) NULL,
    
    -- ETF / Category metadata
    [SingleCategory] NVARCHAR(100) NULL,
    [AssetType] NVARCHAR(50) NULL,
    [ETFType] NVARCHAR(50) NULL,
    [SectorTheme] NVARCHAR(100) NULL,
    [Region] NVARCHAR(100) NULL,
    [ActivePassive] NVARCHAR(50) NULL,
    
    -- ETF metrics
    [NetExpenseRatio] FLOAT NULL,
    [TotalHoldings] FLOAT NULL,
    [AssetsUnderManagement] FLOAT NULL,
    [NetAssetValue] FLOAT NULL,
    [NetAssetValuePercent] FLOAT NULL,
    [NetFlows1Month] FLOAT NULL,
    [NetFlowsPercent1Month] FLOAT NULL,
    [NetFlows3Month] FLOAT NULL,
    [NetFlowsPercent3Month] FLOAT NULL,
    [NetFlowsYTD] FLOAT NULL,
    [NetFlowsPercentYTD] FLOAT NULL,
    [NetFlows1Year] FLOAT NULL,
    [NetFlowsPercent1Year] FLOAT NULL,
    [Return1Year] FLOAT NULL,
    [Return3Year] FLOAT NULL,
    [Return5Year] FLOAT NULL,
    [Return10Year] FLOAT NULL,
    [ReturnSinceInception] FLOAT NULL,
    
    [Tags] NVARCHAR(MAX) NULL,
    
    -- Calculated Properties from FinvizRowExtended
    [PriceCompressionScore] FLOAT NULL,
    [VolatilityRegime] NVARCHAR(20) NULL,
    [DistanceSMA50] FLOAT NULL,
    [PositionIn52WeekRange] FLOAT NULL,
    [TrendDirection] NVARCHAR(20) NULL,
    [TrendStage] NVARCHAR(30) NULL,
    [VolumeConfirmation] FLOAT NULL,
    [SRLevel] NVARCHAR(20) NULL,
    [BreakoutSignal] NVARCHAR(20) NULL,
    [RSIExtreme] NVARCHAR(20) NULL,
    [ConsecutiveTrend] INT NULL,
    [DividendSafety] NVARCHAR(10) NULL,
    [QualityGrade] NVARCHAR(20) NULL,
    [LiquidityStatus] NVARCHAR(20) NULL,
    [HighMomentum] BIT NULL,
    [MeanReversionCandidate] BIT NULL,
    [ValueSafety] BIT NULL,
    [WilliamsPercentR] FLOAT NULL,
    [CCITT] FLOAT NULL,
    [StochasticOscillatorFast] FLOAT NULL,
    [BollingerBandPosition] FLOAT NULL,
    [MomentumDirection] NVARCHAR(30) NULL,
    [ShortInterestSignal] NVARCHAR(30) NULL,
    [VolumeSurge] BIT NULL,
    [MoneyFlow] NVARCHAR(30) NULL,
    [HighOptionsActivity] BIT NULL,
    [RelativeStrength] NVARCHAR(40) NULL,
    [TrendStrengthScore] FLOAT NULL,
    [RiskAdjustedPerformance] FLOAT NULL,
    [LowVolatilityQuality] BIT NULL,
    [HighBetaMomentum] BIT NULL,
    [EarningsProximity] NVARCHAR(50) NULL,
    [GrowthStock] BIT NULL,
    [ValueTrapAvoidSignal] BIT NULL,
    [MomentumConvergence] NVARCHAR(50) NULL,
    [TechnicalSetupScore] FLOAT NULL,
    [RiskScore] FLOAT NULL,
    [AdvancedMeanReversion] BIT NULL,
    [MomentumBurst] BIT NULL,
    [DeepValueTrap] BIT NULL,
    [BreakoutConfirmation] BIT NULL,
    [MarketCapCategory] NVARCHAR(20) NULL,
    
    -- Boolean Flags
    [IsUpTrend] BIT NOT NULL DEFAULT 0,
    [IsDownTrend] BIT NOT NULL DEFAULT 0,
    [IsInBreakout] BIT NOT NULL DEFAULT 0,
    [IsOverSold] BIT NOT NULL DEFAULT 0,
    [IsOverBought] BIT NOT NULL DEFAULT 0,
    [IsQuality] BIT NOT NULL DEFAULT 0,
    [IsHighRsi] BIT NOT NULL DEFAULT 0,
    [IsLowRsi] BIT NOT NULL DEFAULT 0,
    [IsWilliamsOversold] BIT NOT NULL DEFAULT 0,
    [IsWilliamsOverbought] BIT NOT NULL DEFAULT 0,
    [IsHighStochastic] BIT NOT NULL DEFAULT 0,
    [IsLowStochastic] BIT NOT NULL DEFAULT 0,
    [IsOutsideBollinger] BIT NOT NULL DEFAULT 0,
    [IsStrongMomentum] BIT NOT NULL DEFAULT 0,
    [IsBearishShortInterest] BIT NOT NULL DEFAULT 0,
    [IsVolumeSurgeActive] BIT NOT NULL DEFAULT 0,
    [IsSmartMoneyInflow] BIT NOT NULL DEFAULT 0,
    [IsOutperformer] BIT NOT NULL DEFAULT 0,
    [IsLowVolatilityStock] BIT NOT NULL DEFAULT 0,
    [IsHighBetaStock] BIT NOT NULL DEFAULT 0,
    [IsNearEarnings] BIT NOT NULL DEFAULT 0,
    [IsGrowthCandidate] BIT NOT NULL DEFAULT 0,
    [IsValueTrapSafe] BIT NOT NULL DEFAULT 0,
    [IsStrongBullishConvergence] BIT NOT NULL DEFAULT 0,
    [IsStrongBearishConvergence] BIT NOT NULL DEFAULT 0,
    [IsBreakoutConfirmed] BIT NOT NULL DEFAULT 0,
    [IsMomentumBurstActive] BIT NOT NULL DEFAULT 0,
    [IsAdvancedMeanReversionSignal] BIT NOT NULL DEFAULT 0,
    [IsDeepValueTrap] BIT NOT NULL DEFAULT 0,
    
    -- Rank Properties
    [RANK_Performance1Min] INT NULL,
    [RANK_Performance2Min] INT NULL,
    [RANK_Performance3Min] INT NULL,
    [RANK_Performance5Min] INT NULL,
    [RANK_Performance10Min] INT NULL,
    [RANK_Performance15Min] INT NULL,
    [RANK_Performance30Min] INT NULL,
    [RANK_Performance1Hour] INT NULL,
    [RANK_Performance2Hours] INT NULL,
    [RANK_Performance4Hours] INT NULL,
    [RANK_PerformanceWeek] INT NULL,
    [RANK_PerformanceMonth] INT NULL,
    [RANK_PerformanceQuarter] INT NULL,
    [RANK_PerformanceHalfYear] INT NULL,
    [RANK_PerformanceYTD] INT NULL,
    [RANK_PerformanceYear] INT NULL,
    [RANK_Performance3Years] INT NULL,
    [RANK_Performance5Years] INT NULL,
    [RANK_Performance10Years] INT NULL,
    [RANK_RiskAdjustedPerformance] INT NULL,
    [RANK_Beta_Industry] INT NULL,
    [RANK_Beta_Sector] INT NULL,
    [RANK_PS_Industry] INT NULL,
    [RANK_PS_Sector] INT NULL,
    [RANK_PB_Industry] INT NULL,
    [RANK_PB_Sector] INT NULL,
    [RANK_PE_Industry] INT NULL,
    [RANK_PE_Sector] INT NULL,
    [RANK_ForwardPE_Industry] INT NULL,
    [RANK_ForwardPE_Sector] INT NULL,
    [RANK_PFreeCashFlow_Industry] INT NULL,
    [RANK_PFreeCashFlow_Sector] INT NULL,
    [RANK_ReturnOnEquity_Industry] INT NULL,
    [RANK_ReturnOnEquity_Sector] INT NULL,
    [RANK_ReturnOnAssets_Industry] INT NULL,
    [RANK_ReturnOnAssets_Sector] INT NULL,
    [RANK_ReturnOnInvestedCapital_Industry] INT NULL,
    [RANK_ReturnOnInvestedCapital_Sector] INT NULL,
    [RANK_CurrentRatio_Industry] INT NULL,
    [RANK_CurrentRatio_Sector] INT NULL,
    [RANK_QuickRatio_Industry] INT NULL,
    [RANK_QuickRatio_Sector] INT NULL,
    [RANK_LTDebtToEquity_Industry] INT NULL,
    [RANK_LTDebtToEquity_Sector] INT NULL,
    [RANK_TotalDebtToEquity_Industry] INT NULL,
    [RANK_TotalDebtToEquity_Sector] INT NULL,
    [RANK_GrossMargin_Industry] INT NULL,
    [RANK_GrossMargin_Sector] INT NULL,
    [RANK_OperatingMargin_Industry] INT NULL,
    [RANK_OperatingMargin_Sector] INT NULL,
    [RANK_ProfitMargin_Industry] INT NULL,
    [RANK_ProfitMargin_Sector] INT NULL,
    
    -- Industry/Sector Metrics
    [PE_Industry] FLOAT NULL,
    [PE_Sector] FLOAT NULL,
    [ForwardPE_Industry] FLOAT NULL,
    [ForwardPE_Sector] FLOAT NULL
);
