CREATE TABLE [sec].[CoverPage13F]
(
	ACCESSION_NUMBER VARCHAR(25) NOT NULL,
    REPORTCALENDARORQUARTER DATE NOT NULL,
    ISAMENDMENT CHAR(1) NULL,
    AMENDMENTNO INT NULL,
    AMENDMENTTYPE VARCHAR(100) NULL,
    CONFDENIEDEXPIRED CHAR(1) NULL,
    DATEDENIEDEXPIRED DATE NULL,
    DATEREPORTED DATE NULL,
    REASONFORNONCONFIDENTIALITY VARCHAR(500) NULL,
    FILINGMANAGER_NAME VARCHAR(500) NOT NULL,
    FILINGMANAGER_STREET1 VARCHAR(500) NULL,
    FILINGMANAGER_STREET2 VARCHAR(500) NULL,
    FILINGMANAGER_CITY VARCHAR(500) NULL,
    FILINGMANAGER_STATEORCOUNTRY CHAR(2) NULL,
    FILINGMANAGER_ZIPCODE VARCHAR(100) NULL,
    REPORTTYPE VARCHAR(100) NOT NULL,
    FORM13FFILENUMBER VARCHAR(100) NULL,
    PROVIDEINFOFORINSTRUCTION5 CHAR(1) NULL,
    ADDITIONALINFORMATION VARCHAR(MAX) NULL,
    UpdateOn DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (ACCESSION_NUMBER)
)
