CREATE TABLE [sec].InfoTable13F
(
    ACCESSION_NUMBER VARCHAR(25) NOT NULL,
    INFOTABLE_SK NUMERIC(38) NOT NULL,
    NAMEOFISSUER VARCHAR(500) NOT NULL,
    TITLEOFCLASS VARCHAR(500) NOT NULL,
    CUSIP CHAR(9) NOT NULL,
    VALUE NUMERIC(12) NOT NULL,
    SSHPRNAMT NUMERIC(16) NOT NULL,
    SSHPRNAMTTYPE VARCHAR(100) NOT NULL,
    PUTCALL VARCHAR(100) NULL,
    INVESTMENTDISCRETION VARCHAR(100) NOT NULL,
    OTHERMANAGER VARCHAR(500) NULL,
    VOTING_AUTH_SOLE NUMERIC(16) NOT NULL,
    VOTING_AUTH_SHARED NUMERIC(16) NOT NULL,
    VOTING_AUTH_NONE NUMERIC(16) NOT NULL,
    UpdateOn DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (ACCESSION_NUMBER, INFOTABLE_SK)
);
