CREATE TABLE [sec].[SubmissionTable13F]
(
ACCESSION_NUMBER VARCHAR(25) NOT NULL,
    FILING_DATE DATE NOT NULL,
    SUBMISSIONTYPE VARCHAR(100) NOT NULL,
    CIK VARCHAR(100) NOT NULL,
    PERIODOFREPORT DATE NOT NULL,
    UpdateOn DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (ACCESSION_NUMBER)
)
